# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: sungrow2mqtt
version: "1.0.0"
description: This add-on integrates Sungrow SHx inverters into Home Assistant via Modbus TCP using MQTT. It reads register data and automatically provides them as sensors and other entities.
url: 'https://github.com/cyphylax/home-assistant-addons/tree/main/sungrow2mqtt'
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  inverter:
    host: ""
    port: 502
    model: ""
  mqtt:
    host: ""
    port: 1883
    user: ""
    passwd: ""
  scan:
    level: "STANDARD"
    interval: 30
    timeout: 5
    connection: "Sungrow"
  smart_meter: false
  log_level: "INFO"
schema:
  inverter:
    host: str
    port: port
    model: str
  mqtt:
    host: str
    port: port
    user: str
    passwd: password
  scan:
    level: "list(BASIC|STANDARD|DETAIL|ALL)"
    interval: int(10,600)
    timeout: int(3,60)
    connection: "list(Sungrow|Modbus|HTTP)"
  smart_meter: bool
  log_level: "list(INFO|WARNING|ERROR|DEBUG)"
